'use strict';

const DEFAULT_PORT = 3000;

const API_PREFIX = `/api`;

const USER_ARGV_INDEX = 2;

const DEFAULT_COMMAND = `--version`;

const MAX_ID_LENGTH = 5;

const EXIT_CODE = {
  success: 0,
  error: 1
};

const HTTP_STATUS_CODE = {
  OK: 200,
  CREATED: 201,
  NO_CCONTENT: 204,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  NOT_FOUND: 404,
  INTERNAL_SERVER_ERROR: 500
};

const VALIDATION = {
  MIN_TITLE_LENGTH: 30,
  MAX_TITLE_LENGTH: 250,
  MIN_ANNOUNCE_LENGTH: 30,
  MAX_ANNOUNCE_LENGTH: 250,
  MAX_FILL_TEXT_LENGTH: 1000,
  MIN_COMMENT_LENGTH: 20
};

const Env = {
  DEVELOPMENT: `development`,
  PRODUCTION: `production`
};

module.exports = {
  DEFAULT_PORT,
  API_PREFIX,
  USER_ARGV_INDEX,
  DEFAULT_COMMAND,
  MAX_ID_LENGTH,
  HTTP_STATUS_CODE,
  EXIT_CODE,
  VALIDATION,
  Env
};
